PUCUniversityManagementSystem/Controllers/CourseController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UniversityManagementSystem.BLL;
using UniversityManagementSystem.Models;

namespace UniversityManagementSystem.Controllers
{
    public class CourseController : Controller
    {
        DepartmentManager departmentManager=new DepartmentManager();
        SemesterManager semesterManager=new SemesterManager();
        CourseManager courseManager=new CourseManager();
        
        [HttpGet]
        public ActionResult Save()
        {


            List<Department> departments = departmentManager.GetAll().ToList();
             List<Semester> semesters = semesterManager.GetAll.ToList();
            ViewBag.Departments = departments;
            ViewBag.Semesters = semesters;
            return View();
        }

      
        // POST: /Course/Create
        [HttpPost]
        public ActionResult Save(Course aCourse)
        {
            try
            {

                
                    ViewBag.alart = courseManager.Save(aCourse);
                    //ViewBag.Mgs = message;
                    List<Department> departments = departmentManager.GetAll().ToList();
                    List<Semester> semesters = semesterManager.GetAll.ToList();
                    ViewBag.Departments = departments;
                    ViewBag.Semesters = semesters;
                    return View(); 
                
                //return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

       
    }
}

PUCUniversityManagementSystem/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

PUCUniversityManagementSystem/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

PUCUniversityManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title PUC University</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.2.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <link href="~/Content/Style.css" rel="stylesheet" />
    <link href="~/Content/mobiscroll-2.9.5.full.min.css" rel="stylesheet" />
    <link href="~/Content/css/style.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
  
</head>
<body>


    @*<div class="container-fluid">
        <div class="row">

                <ul class="Header">

                    <li><img width="100%" height="500" src="~/images/0.jpg" alt="&quot;Academic building &quot;" /></li>
                    <li><img width="100%" height="500" src="~/images/1.jpg" alt="&quot;Academic building &quot;" /></li>
                    <li><img width="100%" height="500" src="~/images/2.jpg" alt="&quot;Academic building &quot;" /></li>
                    <li><img width="100%" height="500" src="~/images/3.jpg" alt="&quot;Academic building &quot;" /></li>
                    <li><img width="100%" height="500" src="~/images/4.jpg" alt="&quot;Academic building &quot;" /></li>
                    <li class="show"><img width="100%" height="500" src="~/images/5.jpg" alt="&quot;Academic building &quot;" /></li>
                </ul>

            </div>
        </div>*@
     
            <nav class="navbar navbar-custom navbar-fixed-top">
                <div class="container">
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li><img width="80px" height="50px" src="~/images/pucc.png" /></li>
                        
                            <li class="active">@Html.ActionLink("Home", "Index", "Department") <span class="sr-only">(current)</span></li>


                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Department <span class="caret"></span></a>
                                <ul class="dropdown-menu ">
                                    <li>@Html.ActionLink("Save Department", "Save", "Department")</li>
                                    <li role="separator" class="divider"></li>
                                    <li>@Html.ActionLink("View All Departments", "Index", "Department")</li>
                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Course <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Save Course", "Save", "Course")</li>
                                    <li role="separator" class="divider"></li>
                                    <li>@Html.ActionLink("View Course Statics", "ShowCourseStatics", "CourseView")</li>
                                    <li role="separator" class="divider"></li>
                                    <li>@Html.ActionLink("Unassign All Courses", "UnAssign", "UnAssignCourses")</li>

                                </ul>
                            </li>

                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Teacher <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Save Teacher", "Save", "Teacher")</li>
                                    <li role="separator" class="divider"></li>
                                    <li>@Html.ActionLink("Assign Course To Teacher", "AssignCourseToTeacher", "CourseAssignToTeacher")</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Student <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Register Student", "Save", "Student")</li>
                                    <li role="separator" class="divider"></li>
                                    <li>@Html.ActionLink("Enroll Student In A Course", "Enroll", "EnrollStudentInCourse")</li>
                                    <li role="separator" class="divider"></li>
                                    <li>@Html.ActionLink("Save Student Result", "Save", "StudentResult")</li>
                                    <li role="separator" class="divider"></li>
                                    <li>@Html.ActionLink("View Result", "ViewStudentResult", "StudentResult")</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Class Room Allocation <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Allocate Classroom", "Save", "ClassRoom")</li>
                                    <li role="separator" class="divider"></li>
                                    <li>@Html.ActionLink("View Class Schedule", "Index", "ClassRoom")</li>
                                    <li role="separator" class="divider"></li>
                                    <li>@Html.ActionLink("Unallocate All Classrooms", "UnAllocateClassRoom", "ClassRoom")</li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>



            <div class="container body-content">

                @RenderBody()
                <hr />
            </div>

            <div class="well well-sm">
                <div style="text-align: center">
                    <strong>Group PUC_4D </strong>
                </div>
                <div style="text-align: center">
                    <strong>@DateTime.Now </strong>
                </div>
            </div>
            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            <script src="~/Scripts/jquery-2.2.0.js"></script>
            <script src="~/Scripts/jquery.validate.js"></script>
            <script src="~/Content/Scripts/bootstrap-hover-dropdown.min.js"></script>
            <script src="~/Scripts/mobiscroll-2.9.5.full.min.js"></script>

            <script>
                $(function () {
                    $("ul.nav li.dropdown").hover(function () {
                        $(".dropdown-menu", this).fadeIn();
                    }, function () {
                        $(".dropdown-menu", this).fadeOut("fast");
                    });
                })
            </script>
            @RenderSection("scripts", required: false)
     
</body>
</html>